GIT_DIR = $(PACKAGE_NAME)
GIT_URL = git://github.com/jrl-umi3218/$(PACKAGE_NAME).git
GIT_REVISION = master

#FIXME: for now, do not enable OpenHRP plug-in compilation.
CMAKE_EXTRA_ARGS=-DOPENHRP_VERSION_3=

include ../common.mk
