GIT_DIR = $(PACKAGE_NAME)
GIT_URL = git://github.com/jrl-umi3218/dynamic-graph.git
GIT_REVISION = master

CMAKE_EXTRA_ARGS=
#PKG_CONFIG_PATH=$(shell rospack find jrl-mathtools)/install/lib/pkgconfig

include ../common.mk
