GIT_DIR = $(PACKAGE_NAME)
GIT_URL =git://github.com/jrl-umi3218/jrl-mal.git
GIT_REVISION = master

CMAKE_EXTRA_ARGS=-DSMALLMATRIX=jrl-mathtools
PKG_CONFIG_PATH=$(shell rospack find jrl-mathtools)/install/lib/pkgconfig

include ../common.mk
